version: "3.8"
# Run all services

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty

    # this create a folder in your local machine which store data here (it's optional you can remove it if you want)
    volumes:
      - /home/krish/Desktop/data:/data/db
    
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: qwerty
      
  testapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testapp
    ports:
      - 5050:5050
    depends_on:
      - mongo
    environment:
      - AWS_ACCESS_KEY_ID=add_your_AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=add_your_AWS_SECRET_ACCESS_KEY
      - S3_BUCKET=add_your_S3_BUCKET
      - S3_MOUNT_POINT=/s3data
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    # volumes:
    #   - ./app_data:/app/data  # If you need local volume mounting as well
    